export ZSH=$HOME/.dotfiles/zsh/oh-my-zsh
export NVM_DIR=$HOME/.nvm
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin

ZSH_THEME="fino-time"

plugins=(zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/aliases

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
